export const Action = {
  CREATE_NEW_RESOURCE: "CREATE_NEW_RESOURCE",
  GET_RESOURCES: "GET_RESOURCES",
  GET_RESOURCES_BY: "GET_RESOURCES_BY",
  FILTER_RESOURCES_BY_SEARCH: "FILTER_RESOURCES_BY_SEARCH",
}
export const Mutation = {
  SET_NEW_RESOURCE: "SET_NEW_RESOURCE",
  SET_RESOURCE_TAGS: "SET_RESOURCE_TAGS",
  SET_FILTER_BY_TAG: "SET_FILTER_BY_TAG",
  SET_FILTER_BY_SEARCH: "SET_FILTER_BY_SEARCH",
  SET_ERROR: "SET_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR"
}